FROM node:alpine as builder
WORKDIR /usr/app
COPY ./package.json ./
COPY ./yarn.lock ./
RUN yarn install
COPY ./ ./
RUN yarn build
CMD ["npm", "run", "start"]

FROM nginx
EXPOSE 80
COPY --from=builder /usr/app/build /usr/share/nginx/html
