version: "3"
services:
  mymongodb:
    build:
      dockerfile: Dockerfile
      context: ./mongodb
    restart: always
    networks:
      - shoppers
  mynodejsapp:
    depends_on:
      - mymongodb
    build:
      dockerfile: Dockerfile
      context: ./nodejs
    restart: always
    networks:
      - shoppers
    ports:
      - 8000:8000
    environment:
      DATABASE_USER: admin
      DATABASE_PASSWORD: 1111
      DATABASE_HOST: mymongodb
  myreactapp:
    depends_on:
      - mymongodb
      - mynodejsapp
    build:
      dockerfile: Dockerfile.prod
      context: ./frontend
    ports:
      - 3000:80
    restart: always
    networks: 
      - shoppers

networks:
  shoppers:
